mqtt:
  host: "{FRIGATE_MQTT_HOST}"
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

go2rtc:
  streams:
    tapo_c260_bedroom_4k_h265:
      - rtsp://{FRIGATE_TAPO_C260_BEDROOM_USERNAME}:{FRIGATE_TAPO_C260_BEDROOM_PASSWORD}@{FRIGATE_TAPO_C260_BEDROOM_HOST}:554/stream1#tcp#backchannel=false
    tapo_c260_bedroom_720p_h264:
      - rtsp://{FRIGATE_TAPO_C260_BEDROOM_USERNAME}:{FRIGATE_TAPO_C260_BEDROOM_PASSWORD}@{FRIGATE_TAPO_C260_BEDROOM_HOST}:554/stream2#tcp#backchannel=false
    tapo_c260_bedroom_4k_h264:
      - ffmpeg:tapo_c260_bedroom_4k_h265#video=h264#audio=aac

cameras:
  tapo_c260_bedroom:
    live:
      streams:
        "Main (4k, h.264)": tapo_c260_bedroom_4k_h264
        "Sub (4k, h.265)": tapo_c260_bedroom_4k_h265
        "Low quality (720p, h.264)": tapo_c260_bedroom_720p_h264
    onvif:
      host: "{FRIGATE_TAPO_C260_BEDROOM_HOST}"
      port: 2020
      user: "{FRIGATE_TAPO_C260_BEDROOM_USERNAME}"
      password: "{FRIGATE_TAPO_C260_BEDROOM_PASSWORD}"
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_c260_bedroom_4k_h265
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/tapo_c260_bedroom_720p_h264
          input_args: preset-rtsp-restream
          roles:
            - detect

    audio:
      enabled: true
      listen:
        - crying
        - bark

    detect:
      enabled: false

    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 3
          mode: all
      detections:
        retain:
          days: 3
          mode: all

    snapshots:
      enabled: true
      retain:
        default: 3
